# Generated by Django 3.2.4 on 2021-07-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churrasco', '0003_alter_produto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=500, verbose_name='Cidade')),
                ('quantidadePessoa', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Quantidade pessoa')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cidade',
        ),
        migrations.AddField(
            model_name='pedido',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churrasco.informacaopedido'),
        ),
    ]
